# Generated by Django 2.1.3 on 2018-11-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('teams', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Kursant', 'verbose_name_plural': 'Kursanci'},
        ),
        migrations.AddField(
            model_name='student',
            name='exercises',
            field=models.ManyToManyField(through='exams.ExerciseStudent', to='exams.Exercise', verbose_name='Zadania'),
        ),
    ]
